### ISSUE TITLE
Image not showing up

### ISSUE THREAD

**Issue by phoenixthefirebird** [prabhuignoto/react-chrono#101]
**Describe the bug**
Despite following the instruction in README closely, images I link in the media attributes are not showing up in the timeline element at all. Below is how my code looks like.

```
        title: "May 1940",
        cardTitle: "Project 1",
        cardSubtitle:"Description of my amazing project",
        cardDetailedText: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
        media: {
          source: {
            url: "https://cdn.the-scientist.com/assets/articleNo/66820/hImg/34886/bird-banner3-l.png",
            type:"png"
          },
          type: "IMAGE"
        }
      },
```

**Expected behavior**
Image shows up in the timeline card

**Screenshots**
![image](https://user-images.githubusercontent.com/55338489/108800471-15df8f80-7548-11eb-8d31-e71ba43e95a8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

Thanks in advance!

**Comment by prabhuignoto** [comment]
@phoenixthefirebird  Thanks for reporting the issue. Can you point me to the repo to replicate this issue

**Comment by phoenixthefirebird** [comment]
Thank you for your quick reply! Below is the link and I'm using the timeline as the project part of my portfolio. please let me know if you can figure out what's wrong! 

https://github.com/phoenixthefirebird/phoenixthefirebird.github.io.git

**Comment by prabhuignoto** [comment]
I figured the `cardHeight` prop is not getting set for the cards in `vertical` mode. can you manually pass the prop like below.

```sh
<Chrono cardHeight={200} />
```

this will be fixed in the next minor release where you don't need to manually pass this prop. can you check and let me know if this worked for you.

**Comment by phoenixthefirebird** [comment]
It works now and the timeline looks great, thank you so much!

**Comment by prabhuignoto** [comment]
@phoenixthefirebird 
glad it worked. i checked your site, the timelines would look better if its wrapped inside a container.

**Comment by phoenixthefirebird** [comment]
Thank you for the feedback will try it out!
