### ISSUE TITLE
Images and videos are not showing up. 

### ISSUE THREAD

**Issue by naajil-aamir** [prabhuignoto/react-chrono#102]
The image is present in the cards. And when we increase the height of the div, it is seen. However by default, the height of the div containing the media is 0. 

My list of items looks as follows.
```
[{
       "title": "10th Gen Civic",
       "cardTitle": "Honda Civic",
       "cardSubtitle": "The latest Generation of civic",
       "cardDetailedText": "Honda released the 10th generation of the civic in 2016. he Civic has gone through several generational changes, becoming both larger and more upscale, moving into the compact car segment",
       "media": {
        "name": "Honda Civic",
        "type": "IMAGE",
        "source": {
          "url": "civic.jpg",
          "type": "jpg"
        }
      }
    },
    {
       "title": "May 1940",
       "cardTitle": "Dunkirk",
       "cardSubtitle": "Men of the British Expeditionary Force (BEF) wade out to..",
       "cardDetailedText": "Men of the British Expeditionary Force (BEF) wade out to..Men of the British Expeditionary Force (BEF) wade out to..Men of the British Expeditionary Force (BEF) wade out to..Men of the British Expeditionary Force (BEF) wade out to..Men of the British Expeditionary Force (BEF) wade out to..Men of the British Expeditionary Force (BEF) wade out to..Men of the British Expeditionary Force (BEF) wade out to..Men of the British Expeditionary Force (BEF) wade out to..",
       "media": {
        "source": {
          "url": "https://www.youtube.com/embed/f6cz9gtMTeI",
          "type": "mp4"
        },
        "type": "VIDEO",
        "name": "Pearl Harbor"
      }
    }
]
```

**Comment by prabhuignoto** [comment]
@naajil-aamir Thanks for reporting the issue. can you point me to your repo, so that i can replicate the issue locally

**Comment by prabhuignoto** [comment]
@naajil-aamir

I figured the `cardHeight` prop is not getting set for the cards in `vertical` mode. can you manually pass the prop like below for the time being.

```sh
<Chrono cardHeight={200} />
```

this will be fixed in the next patch release where you don't need to manually pass this prop. can you check and let me know if this worked for you.

**Comment by naajil-aamir** [comment]
sure. But I am viewing it in horizontal mode. But that fixed it as well. I also have another issue, The labels are on top of the line, even though I followed everything in the tutorial. 
![image](https://user-images.githubusercontent.com/34787692/109013372-5c9dc880-76b3-11eb-93bb-50c69f3e1ab2.png)
