### ISSUE TITLE
Titles are mispositioned. 

### ISSUE THREAD

**Issue by naajil-aamir** [prabhuignoto/react-chrono#107]
Hi. 
The titles of the timeline are mispositioned. They should be on top of the blue circles but right now they are on the line. I can position the titles using styling(I don't want to do that because of variable length of the titles), but out of the box they are like this
![image](https://user-images.githubusercontent.com/34787692/109499332-0c4caf00-7a95-11eb-9774-25997d796d58.png)

Here is the link to my repository:
https://github.com/naajil-aamir/Timeline.git

**Comment by prabhuignoto** [comment]
@naajil-aamir thanks for reporting the issue. this has been fixed with the latest patch release 1.9.2. can you update the lib recheck this issue.

**Comment by naajil-aamir** [comment]
Hey. It's exactly the same. Didn't fix with the update.

**Comment by 0rsa** [comment]
Same issue with a fresh minimalist install to test it.
I use version 1.12.1

**Comment by prabhuignoto** [comment]
@0rsa is this something that you still see in the latest version. thanks

**Comment by prabhuignoto** [comment]
@naajil-aamir should be fixed with 1.15 release. feel free to reopen if you are still facing this issue.
