### ISSUE TITLE
cardHeight prop is not working in VERTICAL mode

### ISSUE THREAD

**Issue by adityamudgil2505** [prabhuignoto/react-chrono#114]
**Describe the bug**
I am adding cardHeight property to the Chrono component having Vertical mode but nothing changes with the cards. 

**To Reproduce**
1. Clone vertical basic sandbox example given on npm website (https://codesandbox.io/s/react-chrono-vertical-basic-0rm1o?file=/src/App.js)
2. Add "cardHeight" to Chrono component

**Expected behavior**
From what I understand, the cardHeight property makes all cards have a certain minimum height. For example if I set it 700, then all cards will have a minimum of 700 pixels in height. However, in my case, the cards have the minimum height of 200.

**Screenshots**
https://codesandbox.io/s/ug6h3

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 89.0.4389.82

**Comment by prabhuignoto** [comment]
@adityamudgil2505 this has been fixed with the latest release. do check out and let me know how it works for you

**Comment by adityamudgil2505** [comment]
@prabhuignoto It's working fine now. Thanks for looking into this issue.

**Comment by Tushardeepak** [comment]
Not working in projects
![Screenshot (758)](https://user-images.githubusercontent.com/39951979/116807110-e56f2f80-ab4e-11eb-8ad2-2f9fa063b21a.png)
![Screenshot (759)](https://user-images.githubusercontent.com/39951979/116807114-e99b4d00-ab4e-11eb-9ead-0eb9af0a153a.png)
