### ISSUE TITLE
Keep scroll position on auto load

### ISSUE THREAD

**Issue by its-ermira** [prabhuignoto/react-chrono#119]
Hi there! 

On scroll end, I am loading more data to the timeline, and when loading is done, the scrollbar scrolls to the top of the timeline, which is a frustration and not user friendly because I'm loading the new data on the bottom.

Can _scroll to the top_ be disabled for this use case?

**Comment by prabhuignoto** [comment]
@its-ermira can you let me know if there is a repo where i can reproduce this issue.

**Comment by its-ermira** [comment]
@prabhuignoto Here's the issue reproduced
https://codesandbox.io/s/react-chrono-vertical-basic-forked-3bdi0

**Comment by prabhuignoto** [comment]
@its-ermira  this has been fixed with the latest update. do check out and let me know how that works out for you
