### ISSUE TITLE
A new prop, cardWidth, similar in usage to the existing cardHeight.

### ISSUE THREAD

**Issue by aoppenh** [prabhuignoto/react-chrono#125]
I would really like to be able to set a defined cardWidth for the cards appearing in Horizontal mode.  It's fairly simple, just the ability to force the cards to be a certain width the same way we can use cardHeight.

**Comment by prabhuignoto** [comment]
@aoppenh this has been added to 1.9.3 do check and let me know how it works out

**Comment by aoppenh** [comment]
@prabhuignoto Thank you, I tried it out and it works perfectly.
