### ISSUE TITLE
Output HTML markup in cardDetailedText

### ISSUE THREAD

**Issue by broodje** [prabhuignoto/react-chrono#130]
Is there a way to output links or formatted lists in the card text?

I'm trying to build a timeline of user activity with actions taken including links towards the pages where the actions occured.

**Comment by prabhuignoto** [comment]
@broodje have you tried the custom rendering option

https://github.com/prabhuignoto/react-chrono#rendering-custom-content

**Comment by broodje** [comment]
As suggested, i ended up using custom rendering and using .map to generate the correct html.
Using just custom rendering, the HTML was still outputting escaped values and with the usage of .map and flat strings, i build the view in the custom render
