### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by fdw** [prabhuignoto/react-chrono#131]
**Describe the bug**
React-Chrono depends on React 16, but 17 has been released.

**To Reproduce**
1.Try to update to React 17.
2. `npm install` returns this error:
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from react-chrono@1.9.3
npm ERR! node_modules/react-chrono
npm ERR!   react-chrono@"^1.9.3" from the root project
```

**Expected behavior**
It just works

**Comment by fdw** [comment]
Sorry, this was just a hiccup on my setup.

**Comment by mkarbo** [comment]
How did you solve this hiccup?
