### ISSUE TITLE
useReadMore is not available

### ISSUE THREAD

**Issue by OkkarMin** [prabhuignoto/react-chrono#140]
**Describe the bug**
useReadMore props is not available

**To Reproduce**
1. npm i react-chrono
```js
  import React from "react"
  import { Chrono } from "react-chrono";
  
  const Home = () => {
    const items = [{
      title: "May 1940",
      cardTitle: "Dunkirk",
      cardSubtitle:"Men of the British Expeditionary Force (BEF) wade out to..",
      cardDetailedText: "Men of the British Expeditionary Force (BEF) wade out to..",
      media: {
        type: "IMAGE",
        source: {
          url: "http://someurl/image.jpg"
        }
      }
    }, ...];

    return (
      <div style={{ width: "500px", height: "400px" }}>
        <Chrono items={items} useReadMore={false} />
      </div>
    )
  }
```

**Expected behavior**
Read more button should disappear on the cards

**Desktop (please complete the following information):**
 - OS: iOS, MacOS[e.g. iOS]
 - Browser Chrome, Safari, Edge[e.g. chrome, safari]
 - Version 1.9.3

**Comment by tatojoel1** [comment]
I have the same issue too!

Desktop (please complete the following information):
OS: Windows
Browser Chrome, Safari, Edge[e.g. chrome, safari]
Version 1.9.2

**Comment by bastiensun** [comment]
Hi @tatojoel1 !

From what I understand, the `useReadMore` props that allows to enable/disable the "read more" functionality is only available in version 1.9.3 (https://github.com/prabhuignoto/react-chrono/releases).

The default version on npm is 1.9.2 (https://www.npmjs.com/package/react-chrono), so you have to specify explicitly the last version which is 1.9.3 to have the new `useReadMore` props.

**Comment by tatojoel1** [comment]
Hi @bastiensun 
Thanks so much for the answer!
It works!

**Comment by OkkarMin** [comment]
My apologies, I did not check `package.json` and saw the version on the GitHub repo and posted the issue. After explicitly declaring 1.9.3, it works well.
