### ISSUE TITLE
Allow text color override for the selected title

### ISSUE THREAD

**Issue by HadiSDev** [prabhuignoto/react-chrono#145]
**Describe the solution you'd like**
For example if your secondary color does not match as a text color for the primary color then it will look like this:
![image](https://user-images.githubusercontent.com/10367624/124292084-81201a80-db55-11eb-8a8d-e0ea7ec2a8ae.png)

I would like to have the option to decide what the text color should be in the selected (small) box. For example I want the color to be white:
![image](https://user-images.githubusercontent.com/10367624/124292250-a876e780-db55-11eb-8571-e8dd97a005d7.png)

**Comment by prabhuignoto** [comment]
This has been fixed with the 1.10.1 rel. can you update the lib and check.

[example](https://github.com/prabhuignoto/react-chrono#theme)
