### ISSUE TITLE
Widen peer dependency range to include React 17

### ISSUE THREAD

**Issue by janetarzen** [prabhuignoto/react-chrono#159]
**Describe the bug**
Could this be widened to ^16.13.1 || ^17.0.0?

Current values in package.json:
 "peerDependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  }

Purpose of proposed feature:

Allows apps using React 17 to also use react-chrono without peer dependency warnings.

**Comment by prabhuignoto** [comment]
peer dependencies updated with 1.11.0.
