### ISSUE TITLE
allowDynamicUpdate is not working as expected

### ISSUE THREAD

**Issue by bharath3719** [prabhuignoto/react-chrono#164]
If we pass new items with allowDynamicUpdate = false , then the component doesn't update at all.

If we pass new items with allowDynamicUpdate = true , then the component appends the data from pervious position. It does not update the component with the new data.

**Comment by prabhuignoto** [comment]
thanks for trying react-chrono. would you have a repo where i can check this issue.

**Comment by bharath3719** [comment]
I feel react-chrono was designed this way.. So had to clear the state before setting it , which fixed the data being appended issue.
But i do have one new issue/query , the onItemSelected doesnt get fired when i use the Navigation controls...
