### ISSUE TITLE
onItemSelected  is not firing

### ISSUE THREAD

**Issue by bharath3719** [prabhuignoto/react-chrono#167]
onItemSelected  is not firing while using navigation controls

**Comment by prabhuignoto** [comment]
@bharath3719 this has been fixed in the latest release 1.12.0. please check and let me know if you still see the issue

**Comment by bharath3719** [comment]
![image](https://user-images.githubusercontent.com/19222968/133215028-2c71f214-330d-4847-b1a4-3dd0d4a6bde9.png)
I updated to 1.12.0 , and when i use those nav buttons , the event doesnt get fired with the current/prev/first/last scenarios...

**Comment by bharath3719** [comment]
Could you please help me with this today if possible, i am on a deadline..
Or help me how to add some kind of scroll to the div having class "horizontal timeline-main-wrapper" -- so that user can scroll the timeline if the items are more..

**Comment by prabhuignoto** [comment]
Can you paste the link to your repo

**Comment by bharath3719** [comment]
i dont have a public repo.. but i modified the sandbox example.. and forked it
https://codesandbox.io/s/sweet-chihiro-l7otn?file=/src/App.js

**Comment by prabhuignoto** [comment]
looks like there was a packaging issue. can u try upgrading your lib to 1.12.1

**Comment by prabhuignoto** [comment]
@bharath3719 closing this. please reopen if you still see this problem
