### ISSUE TITLE
Card Title Colour

### ISSUE THREAD

**Issue by marcus2k** [prabhuignoto/react-chrono#169]
In the `"VERTICAL"` and `"VERTICAL_ALTERNATING"` modes, the colour of the first card title follows the theme's primary colour, but the subsequent cards do not.

In the following example, the first card title should be green and not red.

![Screen Shot 2021-09-09 at 2 06 53 AM](https://user-images.githubusercontent.com/60178730/132561747-c47d9147-608f-4f00-9757-d16ceb3c7202.png)

The following theme settings was used for the Chrono component:
```
const theme = {
  primary: "red", 
  secondary: "white", 
  textColor: "blue",
  cardBgColor: "white", 
  cardForeColor: "green
  titleColor: "red"
}
```

**Comment by prabhuignoto** [comment]
hey @marcus2k  thanks for posting the issue. can you post the link to the repo please

**Comment by prabhuignoto** [comment]
please reopen if you still see it and attach the link to the repo
