### ISSUE TITLE
Option to disable timeline point selection

### ISSUE THREAD

**Issue by marcus2k** [prabhuignoto/react-chrono#170]
This is a feature request. 

In the `"VERTICAL"` or `"VERTICAL_ALTERNATING"` mode, perhaps a prop can be added to the Chrono component to disable the selection of a point in the timeline.

In the following example, the top-most point is being selected. I am hoping to disable this.

<img width="235" alt="Screen Shot 2021-09-09 at 2 16 28 AM" src="https://user-images.githubusercontent.com/60178730/132563000-a177af1b-4b47-48c6-954a-bde2eb98fd52.png">

Thanks!

**Comment by prabhuignoto** [comment]
@marcus2k is there a specific reason why you want to disable the timeline point selection.

**Comment by PedroSilva8** [comment]
Personally, I want to use Chrono as a simple timeline, I have no need for the point selection, I also believe there should be an option to disable it, when I have the timeline vertically and disable controls there really isn't any use for the point selection

**Comment by Edward-Phillips** [comment]
+1 to this, I would love a prop to disable timeline point selection. Also I just want to say this is a great component 🙌  thanks for the work you do

**Comment by prabhuignoto** [comment]
the width of the line can be customized via `lineWidth` and the circle dimension can be adjusted via `timelineCircleDimension`
