### ISSUE TITLE
Initial item selected

### ISSUE THREAD

**Issue by hhphuc12** [prabhuignoto/react-chrono#171]
Hello,

Is there any way to set the initial item selected for this fantastic library? Thank you!

**Comment by prabhuignoto** [comment]
you can set the prop `active` to true to a specific timeline item that you want to be selected on load.

**Comment by PrateekKumarSingh** [comment]
> you can set the prop `active` to true to a specific timeline item that you want to be selected on load.
> 
> ```shell
>  {
>     title: 'May 1940',
>     cardTitle: 'Dunkirk',
>     media: {
>       name: 'dunkirk beach',
>       source: {
>         url:
>           'https://i2-prod.mirror.co.uk/incoming/article10847802.ece/ALTERNATES/s810/PAY-Dunkirk-in-colour.jpg',
>       },
>       type: 'IMAGE',
>     },
>    active: true
>   },
> ```
> 
> can you check and let me know if this works for you.

Hi @prabhuignoto, 

I tried `active: true` in item data, but it is still not working for me, is there any workaround?

**Comment by Manuelandro** [comment]
Have the same issue, active: true doesn't seem to work

**Comment by prabhuignoto** [comment]
Can you try using the new prop `activeItemIndex` to achieve the selection on load.

https://github.com/prabhuignoto/react-chrono#props

**Comment by prabhuignoto** [comment]
closing this issue. please reopen if you still have issues
