### ISSUE TITLE
Option to disable scroll into view on Item selection

### ISSUE THREAD

**Issue by bharath3719** [prabhuignoto/react-chrono#176]
I have used chrono by hiding the cards , on item selection , i am manually loading a div below the horizontal timeline , without using the card. 

Issue  : The scroll position of the container div gets lost on click.

I think it is due to focus Js , is there any way to just disable the focusing functionality ?

**Comment by prabhuignoto** [comment]
currently there is no way to disable auto focus. i am planning to include a prop to disable this behavior.

**Comment by prabhuignoto** [comment]
use `disableAutoScrollOnClick`  to disable the auto scrolling.
