### ISSUE TITLE
useReadMore on element basis

### ISSUE THREAD

**Issue by gutsytechster** [prabhuignoto/react-chrono#179]
**Is your feature request related to a problem? Please describe.**
At times, there is a very small description for some of the cards in a timeline. However, the `read more` is still shown to the user. It is being used where the description is long, but for one-liner detailed text, it is not required.

**Describe the solution you'd like**
We can specify this prop on each element of the `items` prop, or if it can automatically adds it based on the cardHeight + the amount of content to be shown.

**Describe alternatives you've considered**
An alternative is to define the custom content, to remove the `read more` text.

**Additional context**
If there is any other solution that I am not aware of, please let me know.

Thank you for your work. I found this project very helpful and easy to use. I am not into Frontend much, but it was easier for me to integrate this into my portfolio.

**Comment by prabhuignoto** [comment]
This is now fixed with 1.13. The  read more link only appears if the text content exceeds the card height.
