### ISSUE TITLE
How to send image file as media without giving URL

### ISSUE THREAD

**Issue by VeenaMalali13** [prabhuignoto/react-chrono#182]
Hello,

We can send image file in media giving url to source. But what if I dont have url. I am getting image file from backend API and I need to pass this image file to media. How I can do this? Is it possible with react-chrono?

**Comment by prabhuignoto** [comment]
@VeenaMalali13 have you checked the custom rendering feature. 
https://github.com/prabhuignoto/react-chrono#rendering-custom-content

**Comment by prabhuignoto** [comment]
@VeenaMalali13 closing this for now. please reopen if you are still facing any issues
