### ISSUE TITLE
Slideshow not working

### ISSUE THREAD

**Issue by MarekPrim** [prabhuignoto/react-chrono#184]
**Describe the bug**
The slideshow is not launching when the Play button is clicked

**To Reproduce**
Steps to reproduce the behaviorxs:
1. Go to the horizontal timeline demo [Here](https://codesandbox.io/s/keen-shannon-gtjwn?file=/src/App.js)
2. Add the slideShow attribute to the <Chrono/> component
3. Click on the Play button
4. Observe the things, well, not happening

**Expected behavior**
It should start playing

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome

**Additional context**
It do work with the others vertical demos tough
Edit : It works when an item is selected, but it breaks when no items is selected (e.g. after reloading the page)

**Comment by prabhuignoto** [comment]
@MarekPrim This has been fixed in the latest version of react-chrono.
