### ISSUE TITLE
CardWidth not positioning card to center

### ISSUE THREAD

**Issue by sandheepsebastain** [prabhuignoto/react-chrono#186]
**Describe the bug**
When using the cardWidth property (reduced the card width), it left aligns the card and does not position it to center. Mode is HORIZONTAL

**To Reproduce**
Add cardWidth="200"

**Expected behavior**
Reducing the cardWidth would also align the card to the center 

**Screenshots**
![image](https://user-images.githubusercontent.com/22875118/142765122-6cf420c5-838c-4af1-8177-1f892b44e5a3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**
Reached this bug by trying to see how react-chrono will look in mobile mode. Using the current cardWidth, text is cut off at the corners.

**Comment by prabhuignoto** [comment]
@sandheepsebastain this is been fixed with 1.13.
