### ISSUE TITLE
Cypress is a dependency

### ISSUE THREAD

**Issue by Johannes-Andersen** [prabhuignoto/react-chrono#188]
**Describe the bug**
It seems as part of [this](https://github.com/prabhuignoto/react-chrono/commit/5c92fdbfce02b8baaea20065ead1f21b092be0e8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) commit, Cypress got moved to dependencies object instead of keeping it in devDependencies

**Expected behavior**
Cypress should be in the devDependencies object

**Screenshots**
<img width="918" alt="Screenshot 2021-11-22 at 16 09 50" src="https://user-images.githubusercontent.com/57638117/142895708-90488f3e-5cca-4106-8aa0-db10d74fe234.png">

**Additional context**
npm audit now complains that there is vulnerability

```
> npm audit
# npm audit report

json-schema  <0.4.0
Severity: moderate
json-schema is vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-896r-f27r-55mw
fix available via `npm audit fix --force`
Will install react-chrono@1.12.1, which is a breaking change
node_modules/json-schema
  jsprim  0.3.0 - 2.0.1
  Depends on vulnerable versions of json-schema
  node_modules/jsprim
    http-signature  1.0.0 - 1.3.5
    Depends on vulnerable versions of jsprim
    node_modules/http-signature
      @cypress/request  *
      Depends on vulnerable versions of http-signature
      node_modules/@cypress/request
        cypress  >=4.3.0
        Depends on vulnerable versions of @cypress/request
        node_modules/cypress
          react-chrono  >=1.12.2
          Depends on vulnerable versions of cypress
          node_modules/react-chrono

6 moderate severity vulnerabilities
```

**Comment by prabhuignoto** [comment]
@Johannes-Andersen thanks for flagging this. cypress now is a dev dependency.
