### ISSUE TITLE
Multiple chrono component don't display card correctly.

### ISSUE THREAD

**Issue by virurathore** [prabhuignoto/react-chrono#191]
**Describe the bug**
Multiple chrono component don't display card correctly.

**To Reproduce**
codesend box
https://codesandbox.io/s/keen-shannon-gtjwn?file=/src/App.js
create multiple chrono component as below.
 `   <div className="App">
      <div style={{ width: "850px", height: "500px" }}>
        <Chrono items={data} mode="HORIZONTAL" />
      </div>
      <Chrono items={data} mode="HORIZONTAL" />
    </div>`
both card display on same block/row and only one card replaced, whichever timeline dot clicked.
**Expected behavior**
both card should display with respective timeline.

**Screenshots**
![image](https://user-images.githubusercontent.com/21017275/143042131-893f9bb4-1342-4b3e-94fc-0f6c5508a8d6.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome

**Comment by prabhuignoto** [comment]
@virurathore this is now fixed
