### ISSUE TITLE
RTL Support for horizontal view

### ISSUE THREAD

**Issue by mohsenomidi** [prabhuignoto/react-chrono#194]
**Describe the solution you'd like**
When using the horizontal time line there is no RTL property to showing the timeline correctly, is there any plan to add this feature ?

**Comment by prabhuignoto** [comment]
the horizontal timeline is getting a complete refactor and you should see the RTL support available with the 1.13 release.

**Comment by mohsenomidi** [comment]
Thank you so much, I will check the next release and feedback 
This is very important to multi language applications. 🙏🙏

**Comment by mohsenomidi** [comment]
Dear @prabhuignoto 

As far as changing the milestone to support RTL, do you have any ideas about the estimated release date for this feature?

**Comment by prabhuignoto** [comment]
please use `flipLayout` prop to enable RTL  on horizontal mode.
