### ISSUE TITLE
Show more than one cardItem in horizontal mode.

### ISSUE THREAD

**Issue by rawandeheliah** [prabhuignoto/react-chrono#196]
**react-chrono current behaviour for horizontal mode :** only one card is being shown "the selected one" . 

**Is there anyway to show all cards for selected timeline in horizontal mode** , the same way more than one card is shown in vertical mode  ?

**Comment by prabhuignoto** [comment]
@rawandeheliah can you elaborate on showing all cards for a selected timeline. there can be only one card associated with a timeline item. i do agree that it would be nice to display multiple cards instead of just one

**Comment by rawandeheliah** [comment]
I mean about showing all cards : 
I want horizontal mode to show more than one card as in vertical mode , as in this screenshot :
<img width="724" alt="Screen Shot 2021-12-16 at 12 23 32" src="https://user-images.githubusercontent.com/25617782/146354001-00dc625c-a4d6-4d93-9544-f33ecb43cf9d.png">

but in horizontal mode there is only one card [the selected one] is showing as in this screenshot : 
<img width="743" alt="Screen Shot 2021-12-08 at 10 49 29" src="https://user-images.githubusercontent.com/25617782/146354207-253a039a-31ad-466a-9788-e62843095419.png">

**Comment by rawandeheliah** [comment]
regarding this issue , I started adding this feature , and I will post a PR when ready .

**Comment by rawandeheliah** [comment]
[PR](https://github.com/prabhuignoto/react-chrono/pull/207)

**Comment by prabhuignoto** [comment]
this can be done using the new prop `showAllCardsHorizontal`. [example](https://codesandbox.io/s/show-all-cards-5vuf2x?file=/src/App.js)
