### ISSUE TITLE
Scrollbar fix is not working.

### ISSUE THREAD

**Issue by NaveenkumarMD** [prabhuignoto/react-chrono#216]
This is now fixed with  [1.13.1](https://github.com/prabhuignoto/react-chrono/releases/tag/1.13.1).
As you fixed the issue ,I have Installed the latest version but still the scrollbar is visible.Or can you provide any css props to hide it or just change the color of it to transparent.
### package.json
```
  "dependencies": {
    "react": "^17.0.2",
    "react-chrono": "^1.13.1",
    "react-dom": "^17.0.2",
    "react-router-dom": "^6.2.1",
    "react-scripts": "5.0.0"
  },
```
![image](https://user-images.githubusercontent.com/72449129/149645201-e1634ba4-453c-480a-b94f-32f3511743e4.png)

_Originally posted by @prabhuignoto in https://github.com/prabhuignoto/react-chrono/issues/214#issuecomment-1013730870_

**Comment by prabhuignoto** [comment]
are you setting this prop 

```sh
scrollable={{scrollBar: false}}
```

**Comment by NaveenkumarMD** [comment]
Yes

**Comment by prabhuignoto** [comment]
can you try removing the scrollable prop altogether?

**Comment by prabhuignoto** [comment]
> Yes

did removing the prop solved the issue
