### ISSUE TITLE
Horizontal doesn't look as what was provided. 

### ISSUE THREAD

**Issue by Leykwan132** [prabhuignoto/react-chrono#219]
![image](https://user-images.githubusercontent.com/56620672/150157187-0c20a77e-3a8f-4fc1-8a1c-58e1a1296580.png)
What should I alter to the props to make it similar? 

`<div style={{ width: "auto", height: "auto" }}>
        <Chrono items={items} />
      </div>`

**Comment by prabhuignoto** [comment]
can you share the repo to reproduce the issue

**Comment by Leykwan132** [comment]
https://github.com/Leykwan132/personal-web 

Please check if it is working.

**Comment by prabhuignoto** [comment]
the `mode` prop seems to be missing which is what is causing the broken layout.

can you try this and see if it works for you

```sh
<div style={{ width: "850px", height: "500px" }}>
    <Chrono items={items} mode="HORIZONTAL" />
  </div>
```

**Comment by Leykwan132** [comment]
thanks that did the trick! I thought the documentation was saying the mode was HORIZONTAL by default. but thanks anyway! the timeline looks awesome now!

**Comment by prabhuignoto** [comment]
tracked here
https://github.com/prabhuignoto/react-chrono/projects/4#card-76345732
