### ISSUE TITLE
card customization

### ISSUE THREAD

**Issue by kerkar30** [prabhuignoto/react-chrono#224]
complete customisation of the card

**Comment by prabhuignoto** [comment]
@kerkar30 can you elaborate exactly what is that you want to customize in the card. title, content , image or something else

**Comment by dem4ron** [comment]
> complete customisation of the card

If you are looking for a way of full customization, you can pass in divs as children, and style that the way you want. if you don't need any of the preset, prestyled card, you can simply set cardBgColor:'transparent'. 
Hope this is what you were looking for.

**Comment by prabhuignoto** [comment]
@kerkar30 here is an example for the card customization 
https://codesandbox.io/s/react-chrono-vertical-custom-qepnm
