### ISSUE TITLE
not rerending when state change

### ISSUE THREAD

**Issue by Diagru25** [prabhuignoto/react-chrono#237]
Hi everyone.
I have 1 problem with chrono. I set items={timelinePrediction}, default I set timelinePrediction=[], after I use redux-saga to call data and update timelinePrediction. but component Chrono not rerending.
![image](https://user-images.githubusercontent.com/31183495/158617836-19097c7f-b76a-4011-a3ba-feebf6f24f21.png)
this is my code.
thanks all!

**Comment by prabhuignoto** [comment]
is there a repo to reproduce this issue.

**Comment by maxschroen** [comment]
@Diagru25 
Have you tried setting the allowDynamicUpdate prop inside of your Chrono component like so:

```
<Chrono
                items={timelinePrediction}
                allowDynamicUpdate={true}
                mode="VERTICAL_ALTERNATING"
/>
```

This solved my problem when trying to update the state but not having a re-render triggered.

**Comment by Diagru25** [comment]
> @Diagru25 Have you tried setting the allowDynamicUpdate prop inside of your Chrono component like so:
> 
> ```
> <Chrono
>     items={timelinePrediction}
>     allowDynamicUpdate={true}
>     mode="VERTICAL_ALTERNATING"
> />
> ```
> 
> This solved my problem when trying to update the state but not having a re-render triggered.

Thanks. It's works for me.
