### ISSUE TITLE
Customize Navigation Button Text

### ISSUE THREAD

**Issue by mohsenomidi** [prabhuignoto/react-chrono#239]
**Is your feature request related to a problem? Please describe.**

In multi language applications need to change the alt message for each navigation button for accessibility, but there is not an option to pass the custom term for them.

**Describe the solution you'd like**
put some option in props to set the displayed message for each alt message.

**Describe alternatives you've considered**
there is no alternative just use english next and previous message for other languages, and it is not good idea

**Comment by prabhuignoto** [comment]
This is now possible with the new [`buttonTexts`](https://github.com/prabhuignoto/react-chrono#customize-alt-text-for-buttons) prop available in the new release.
