### ISSUE TITLE
Can not update state inside Chrono tag

### ISSUE THREAD

**Issue by qmup** [prabhuignoto/react-chrono#241]
I tried to update state inside the Chrono tag but it didn't work.
As you can see in this [Codesandbox](https://codesandbox.io/s/happy-lake-8dpmit?file=/src/App.js):

Step 1: Clicking button
Step 2: State's changed.
Step 3: Clicking another button
Step 4: State didn't change.

**Comment by NotArpit** [comment]
Having the same issue ... seems the <Chrono /> component does not support re-renders through state updates

**Comment by prabhuignoto** [comment]
This is now fixed with [1.17.2](https://github.com/prabhuignoto/react-chrono/releases/tag/1.17.2)
