### ISSUE TITLE
The new fontSizes function doesn't work with items media config

### ISSUE THREAD

**Issue by stephenhibbert** [prabhuignoto/react-chrono#253]
**Describe the bug**

**To Reproduce**

Set fontSizes with non-default setting and use data items.. some with media elements and others without. Observe that the media items don't respect the custom font sizes but the items without media elements do.

 ```
**App.js**

         fontSizes={{
            cardSubtitle: "0.85rem",
            cardText: "0.8rem",
            cardTitle: "10rem"
          }}


**data.js**

const items = [
  {
    title: "May 1940",
    cardTitle: "Dunkirk",
    cardSubtitle:
      "Men of the British Expeditionary Force (BEF...`,
    media: {
      name: "dunkirk beach",
      source: {
        url: "http://someurl/image.jpg"
      },
      type: "IMAGE"
    }
  },
  {
    title: "25 July 1940",
    cardTitle: "The Battle of Britain",
    cardSubtitle: `RAF Spitfire pilots scramble for their planes`,
    cardDetailedText: `After France’s surrender in June 1940...`
  },

```
**Expected behavior**
The custom font size should always be respected, regardless of the media config.

**Screenshots**
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/11485349/171119925-371c1ae9-f446-4204-9c6c-008b5ccd717b.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: Version 101.0.4951.64 (Official Build) (arm64)

**Additional context**

**Comment by prabhuignoto** [comment]
@stephenhibbert this is now fixed in the new release.

**Comment by stephenhibbert** [comment]
Awesome, thanks for the note - all working as expected now! Thanks for the quick fix and for the awesome project :)
