### ISSUE TITLE
Item title customization

### ISSUE THREAD

**Issue by Eduardo-Maia98** [prabhuignoto/react-chrono#254]
Hi,
Could be added the option to change item title size and color when is not selected, instead of all black.
Thanks, i love this timeline, really good work !!
![image](https://user-images.githubusercontent.com/49003509/171281637-703d9068-ded4-44b5-95a4-ebd54f3a17a0.png)

**Comment by prabhuignoto** [comment]
closing this as fixed, as this can be now customized via the [Theme](https://github.com/prabhuignoto/react-chrono#theme) properties
