### ISSUE TITLE
activeItemIndex is respected in horizontal mode

### ISSUE THREAD

**Issue by danr-za** [prabhuignoto/react-chrono#258]
**Describe the bug**
Setting `activeItemIndex` prop in horizontal mode is not setting the active item.
In vertical mode, it works as expected.

**To Reproduce**
Set `activeItemIndex` to an index that isn't the first.

**Expected behavior**
Should set the active item

**Comment by prabhuignoto** [comment]
@danr-za do you a repo to reproduce this issue. i dont see this happening with the latest version.

**Comment by prabhuignoto** [comment]
@omer-shlifka this is now fixed with the latest version
