### ISSUE TITLE
Support custom className attribute

### ISSUE THREAD

**Issue by bigbigDreamer** [prabhuignoto/react-chrono#268]
Support custom className attribute, sometimes we need custom styles to override component style behavior.

look like as follow:

```tsx
import classes from 'classnames'


const cls = classes('origin-timeline-cls',  className, xxxx)
```

**Comment by prabhuignoto** [comment]
@bigbigDreamer you can now apply custom class names for the different timeline elements.

example here: https://codesandbox.io/s/react-chrono-vertical-basic-forked-uo6tt3?file=/src/App.js

**Comment by bigbigDreamer** [comment]
> @bigbigDreamer you can now apply custom class names for the different timeline elements.
> 
> example here: https://codesandbox.io/s/react-chrono-vertical-basic-forked-uo6tt3?file=/src/App.js

Excellent！thk
