### ISSUE TITLE
Altering cardPositionHorizontal alters position of controls and not timeline card

### ISSUE THREAD

**Issue by torland-klev** [prabhuignoto/react-chrono#271]
**Describe the bug**
When the `Chrono`-component has `mode="HORIZONTAL"`, `cardPositionHorizontal="TOP"` and `hideControls={false}`, the cards are still placed below the timeline. Instead, the timeline controls are placed above the timeline. The expected functionality is restored when `hideControls={true}` is set.

**To Reproduce**
1. Render a component similar to 
```
<Chrono
    items={[
        {
            title: 'May 1940',
            cardTitle: 'Dunkirk',
            cardSubtitle:
                'Men of the British Expeditionary Force (BEF) wade out to..',
        },
    ]}
    mode="HORIZONTAL"
    hideControls={false}
    cardPositionHorizontal="TOP"
/>
```
2. Check that component looks something similar to the screenshot below.

**Expected behavior**
The controls should still be on bottom, while the card should be on top.

**Screenshots**
![image](https://user-images.githubusercontent.com/43351827/180978231-93527ebc-5340-4e2b-aa77-14b68f84846d.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [1.17.2]

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by prabhuignoto** [comment]
@torland-klev This has been fixed with the new release. Please checkout and let me know.

**Comment by opheliaprillard22** [comment]
@prabhuignoto Hi, I have the same issue in version ^2.6.1
