### ISSUE TITLE
Default mode is different from documentation

### ISSUE THREAD

**Issue by torland-klev** [prabhuignoto/react-chrono#272]
**Describe the bug**
The documentation states that the default mode is HORIZONTAL, while the observed default mode is VERTICAL_ALTERNATING.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [1.17.2]

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by prabhuignoto** [comment]
@torland-klev Thanks for flagging this. Its now fixed in the docs
