### ISSUE TITLE
Disable scrollIntoView via props

### ISSUE THREAD

**Issue by torland-klev** [prabhuignoto/react-chrono#273]
**Is your feature request related to a problem? Please describe.**
When entering a page with a timeline, the page auto scrolls to the component. This is incredibly frustrating.

**Describe the solution you'd like**
Control the scrollIntoView via a prop

**Describe alternatives you've considered**
Remove scrollIntoView entirely. It can always be added through a wrapper.

**Additional context**
I currently "disable" it using this function
```
function repeat(func: () => void, times: number, timeout: number) {
    func()
    times && --times && setTimeout(func, timeout)
}

repeat(
    function () {
        // eslint-disable-next-line no-restricted-globals
        scroll(0, 0)
    },
    2,
    200
)
```

**Comment by prabhuignoto** [comment]
with the [0.18.0](https://github.com/prabhuignoto/react-chrono/releases/tag/1.18.0) release, the timeline will not auto scroll on load any more. To focus an item on load, you need to set `focusActiveItemOnLoad` to true and specify the index via `activeItemIndex`

**Comment by shruthi-racha** [comment]
> **Is your feature request related to a problem? Please describe.** When entering a page with a timeline, the page auto scrolls to the component. This is incredibly frustrating.
> 
> **Describe the solution you'd like** Control the scrollIntoView via a prop
> 
> **Describe alternatives you've considered** Remove scrollIntoView entirely. It can always be added through a wrapper.
> 
> **Additional context** I currently "disable" it using this function
> 
> ```
> function repeat(func: () => void, times: number, timeout: number) {
>     func()
>     times && --times && setTimeout(func, timeout)
> }
> 
> repeat(
>     function () {
>         // eslint-disable-next-line no-restricted-globals
>         scroll(0, 0)
>     },
>     2,
>     200
> )
> ```

@torland-klev where should we add this code snippet? Is it in the page that has the timeline as one of the components?
