### ISSUE TITLE
Change min height of images in the timeline cards

### ISSUE THREAD

**Issue by BATspock** [prabhuignoto/react-chrono#276]
When working with chrono on hand held devices the min height specified for image is 100px, this sometimes leads to awkward gaps between image and card's text

Request:
The min height should be customizable or the min height of the images should be set to a relative value instead of a hard stop at 100px

I have added a screen shot from a mobile device

![image](https://user-images.githubusercontent.com/30798316/182146608-598a2e87-7ac0-4a0b-b97b-76c55e3db15e.png)

**Comment by BATspock** [comment]
Is there any update on this?

**Comment by prabhuignoto** [comment]
@BATspock fix is underway along with the few other minor improvements.  Thanks for the patience

**Comment by prabhuignoto** [comment]
@BATspock new prop `mediHeight` has been added to customize the height of the media elements in the card.
