### ISSUE TITLE
Injecting HTML into each timeline

### ISSUE THREAD

**Issue by RaniGiterman** [prabhuignoto/react-chrono#277]
**Is your feature request related to a problem? Please describe.**
Yes. for example, creating a button inside of a timeline. I am unable to do this currently, as if I try to add the ``` <button> ``` tag it will still render as normal text.

**Describe the solution you'd like**
When rendering items by the `items` prop, I would like the properties to be rendered as HTML instead of plain text. For example:
```
const items = [
    {
      title: "<h1>May 1940</h1>;",
      cardTitle: "<b>Dunkirk</b>",
    },
  ];

  return (
          <Chrono
            onItemSelected={selected}
            items={itemsA}
            flipLayout={true}
            theme={{
              primary: "black",
              secondary: "gray",
              cardBgColor: "white",
              cardForeColor: "black",
              titleColor: "black",
              titleColorActive: "white",
            }}
          />
  );

```
items[0].title, items[0].cardTitle would be rendered as HTML ``` <h1> ``` and ``` <b> ``` tags.

**Comment by prabhuignoto** [comment]
@RaniGiterman `title` and `cardTitle` can only accept plain strings at the moment. you might also want to take a look at the custom rendering option. 

here is an example
https://codesandbox.io/s/react-chrono-vertical-custom-2-uctcp?file=/src/App.js
