### ISSUE TITLE
On mouseover (hover) highlight corresponding card or timeline event

### ISSUE THREAD

**Issue by jnachtigall** [prabhuignoto/react-chrono#285]
When the user hovers (mouseover) with the mouse over a timeline event the corresponding card should be highlighted, for instance in the form of a slight colorish border. The same vice versa: When hovering over a card, highlight the related event.

Is there a prop for this or another way to implement this?

**Comment by jnachtigall** [comment]
@prabhuignoto As long as there's no prop for this do you think it is feasible to achieve the same effect via `onMouseEnter` and `onMouseLeave` in some way at the app level? That is, attaching some kind of event handler to the custom card renderer and then setting some CSS class. But I am not sure how this would work for the timeline dot item? Any thoughts for a workaround?

**Comment by prabhuignoto** [comment]
@jnachtigall Unfortunately, there isn't a fix available right now. In order to enable this behavior, I'm adding a new prop. A minor release will shortly be available.
