### ISSUE TITLE
Auto Scrolling not working

### ISSUE THREAD

**Issue by GeorgeMahlangu** [prabhuignoto/react-chrono#287]
When the navigations buttons or items are clicked the timeline is not auto scrolling to the clicked item

**Comment by prabhuignoto** [comment]
can you confirm on which mode you are facing this issue. `HORIZONTAL` or `VERTICAL`

**Comment by prabhuignoto** [comment]
@GeorgeMahlangu closing this as stale, let me know if you are still facing this issue
