### ISSUE TITLE
Stop autoscrolling to card top on HORIZONTAL mode

### ISSUE THREAD

**Issue by leostevanato** [prabhuignoto/react-chrono#290]
Hello!

When using HORIZONTAL mode the page autoscrolls to the top of the current card. It happens when the page is loaded and when we are navigating between cards, be it clicking the nav buttons or the keyboard keys.

You can see the exact same behaviour in this official example:
[Link](https://5f985eb478dcb00022cfd60e-uiaufmxbhf.chromatic.com/?path=/story/example-horizontal--horizontal-timeline)

I'm using the timeline on the middle of the page and when the page is loaded it scrolls down to the timeline. Then, every time I navigate between cards, the page scrolls to the card top and I have to scroll the page up to be able to see the timeline and the nav buttons.

If that is not a bug, it would be nice to have the option to disable it.

I'm using package version 1.19.1 and React version 18.2.0.

Here is an example of my component code:
```
import { Chrono } from "react-chrono";

const timelineTitles= [{ "title": "1971" }, { "title": "1997" }, { "title": "2000" }];

export default () => {
  return (
    <Chrono
      items={ timelineTitles }
      mode="HORIZONTAL"
      fontSizes={ {
        title: '1.5rem'
      } }
      theme={ {
        primary: '#146646',
        secondary: '#E8E8E7',
        cardBgColor: '#EBF3EC',
        titleColor: '#146646',
        titleColorActive: '#146646',
      } }
      cardWidth='1140'
      cardHeight='30'
      disableAutoScrollOnClick='true'
    >
      <div>
        <h3>ITEM 1</h3>
      </div>
      <div>
        <h3>ITEM 2</h3>
        <p>Item text 2</p>
      </div>
      <div>
        <h3>ITEM 3</h3>
        <p>Item text 3</p>
      </div>
    </Chrono >
  );
};
```

Thank you!

**Comment by prabhuignoto** [comment]
have you tried setting `focusActiveItemOnLoad` to false and see if that works.

**Comment by leostevanato** [comment]
@prabhuignoto I tested `focusActiveItemOnLoad` now and it still not works. Please, check my code below to see if I've set it correctly. But even if it is not set in my codeI can see thought a react chorme extension that `focusActiveItemOnLoad` is set to false by default.
```
return (
    <Chrono
      items={ linhaTempoJSON }
      mode="HORIZONTAL"
      focusActiveItemOnLoad='false' // <- ADDED IT HERE
    >
      <div>
        ...
```
I was checking your [example-horizontal--horizontal-timeline](https://5f985eb478dcb00022cfd60e-uiaufmxbhf.chromatic.com/?path=/story/example-horizontal--horizontal-timeline) and noticed that `focusActiveItemOnLoad` is set to **false**, but the page still scrolls to the card on load and on interactions.

Don't you think that there may be a **bug** in the code regarding that setting?

**Comment by shruthi-racha** [comment]
I'm also facing the same issue.

**Comment by shruthi-racha** [comment]
I see this issue was reported earlier as well, and said it was fixed in an earlier version https://github.com/prabhuignoto/react-chrono/issues/273... Why are we still facing this issue then?

**Comment by alonwillmakeit** [comment]
Facing the same things.. :3

**Comment by shruthi-racha** [comment]
@prabhuignoto any workarounds that we could try for this while this bug is picked up for fixing?

**Comment by prabhuignoto** [comment]
@shruthi-racha this is now fixed with the latest patch [release](https://www.npmjs.com/package/react-chrono/v/1.19.2)

**Comment by shruthi-racha** [comment]
> @shruthi-racha this is now fixed with the latest patch [release](https://www.npmjs.com/package/react-chrono/v/1.19.2)

@prabhuignoto thank you! I  upgraded and the fix works!
