### ISSUE TITLE
Visual only mode (no nodes selected)

### ISSUE THREAD

**Issue by MelissaHoweEmis** [prabhuignoto/react-chrono#294]
**Is your feature request related to a problem? Please describe.**
Currently a node has to be active, I would like a visual only timeline where no node is highlighted

**Describe the solution you'd like**
For there to be a flag to set no node as selected

**Describe alternatives you've considered**
Tried setting disableClickOnCircle but the mouse still changes to a pointer when not clickable, and you still have a node set as active.

**Additional context**
For a more visual timeline to represent a history without the need to interact

**Comment by prabhuignoto** [comment]
@MelissaHoweEmis a new prop will be added to disable the interaction. A new minor release to fix this will be out soon.

**Comment by prabhuignoto** [comment]
@MelissaHoweEmis relooking at this request again. have you tried using the `disableAutoScrollOnClick` prop. Can you confirm if this solves the issue.

**Comment by MelissaHoweEmis** [comment]
Im afraid it doesnt solve the issue that when disableClickOnCircle and disableAutoScrollOnClick are set to true, the mouse cursor changes on hover of the nodes. When they aren't clickable I would assume the mouse wouldn't change. They also still have a role of button which implies they are clickable too, I would expect the role to be undefined when they are not interactive.

As an additiona, I think a prop of viewOnly or something similar to the entire timeline would be good as it means you cannot interact with any element of it, and no nodes are marked as selected.
