### ISSUE TITLE
Showing title of timeline event when rendering custom content

### ISSUE THREAD

**Issue by jnachtigall** [prabhuignoto/react-chrono#298]
**Describe the bug**
I would like to use custom card content. But at the same time I would like to use a timeline title.

**To Reproduce**
See this example at https://codesandbox.io/s/fast-surf-ockx4p?file=/src/App.js

Without `items={items}` being passed as prop, I have a fully custom content and also a card title. But I also want the title of the timeline event to be displayed - how would I do this?

With  `items={items}` the title of the timeline event is shown. However, then other markup is added,  like a `<section>` and an empty extra `header` tag, so that the custom content gets "polluted":

![image](https://user-images.githubusercontent.com/3307404/200578538-83fcc327-78eb-45e5-bd22-d6278cf4caae.png)

**Expected behavior**

Show ***title*** of the timeline event when custom card is used.

**Comment by prabhuignoto** [comment]
@jnachtigall this is now possible via the new `timelineContent` property of each timeline object. please note `timelineContent` has higher precedence over `cardDetailedText`

Example:
```js
const items = [
  { title: 'Timeline title 1', cardTitle: 'Card Title 1' },
  { title: 'Timeline title 2', cardTitle: 'Card Title 2', timelineContent: <span>Test</span> },
];

<Chrono mode="VERTICAL" items={items}>
</Chrono>;
```

[Timeline item properties](https://github.com/prabhuignoto/react-chrono#timeline-item-model)
