### ISSUE TITLE
I m having an issue while using with React Router Hash Link not going towards proper section

### ISSUE THREAD

**Issue by JavaidAhmadKhan** [prabhuignoto/react-chrono#305]
I m having an issue while using with React Router Hash Link not going towards proper section using id's I checked it is only happening because of this library, if I remove it in a component everything works.

**Comment by prabhuignoto** [comment]
can  you share the link to the repo?

**Comment by JavaidAhmadKhan** [comment]
it is not a personal project, I have done it for the company so can't share github repository. 

https://ayana-powerv2.vercel.app/

this is the test link

**Comment by prabhuignoto** [comment]
@JavaidAhmadKhan is this still an issue i checked your site and i was able to navigate to the milestone. closing this for now.
