### ISSUE TITLE
The property `timelineContent` isn't working for the HORIZONTAL mode.

### ISSUE THREAD

**Issue by miral-zymr** [prabhuignoto/react-chrono#322]
**Describe the bug**
The property `timelineContent` isn't working for the `mode=HORIZONTAL`. On inspecting, it's not rendering the content mentioned with this property.

**To Reproduce**
```
const items = [
  { title: 'Timeline title 1', cardTitle: 'Card Title 1' },
  { title: 'Timeline title 2', cardTitle: 'Card Title 2', timelineContent: <span>Test</span> },
];

<Chrono mode="HORIZONTAL" items={items} />;
```

**Expected behavior**
Custom React components should be rendered.

CodeSandbox: https://codesandbox.io/s/infallible-microservice-yzfjvz?file=/src/App.js

**Comment by prabhuignoto** [comment]
@miral-zymr This is now fixed with the latest version. you can check and confirm if everything is alright now

**Comment by miral-zymr** [comment]
Thanks, @prabhuignoto! This is a great help. Grateful for such a quick response and fix!
