### ISSUE TITLE
`onItemSelected` is getting called twice when selecting item from the timeline dot.

### ISSUE THREAD

**Issue by miral-zymr** [prabhuignoto/react-chrono#324]
**Describe the bug**
`onItemSelected` is getting called twice when selecting item from the timeline dot. Any method defined here, gets called once when the page loads for the first time. But, when I try to change/select the timeline object, it is getting called twice.

**To Reproduce**
```
const updateSelectedScanItem = (event) => {
    console.log("Event", event);
};

<Chrono
  items={scanItems}
  mode="HORIZONTAL"
  onItemSelected={updateSelectedScanItem}
/>
```

**Expected behavior**
The method defined on this call should only be called once. It is being called once, when the page renders, or if we navigate through the controls, which is expected.

CodeSandbox: https://codesandbox.io/s/infallible-microservice-yzfjvz?file=/src/App.js

P.S. It is on **v1.21.1**

**Comment by miral-zymr** [comment]
@prabhuignoto I apologize, but I'm a little tight deadline here. Is it possible that this issue could be expedited, or is there any chance that you've looked into it?

**Comment by prabhuignoto** [comment]
@miral-zymr this is being looked into. there will be a patch release pretty soon for this

**Comment by miral-zymr** [comment]
@prabhuignoto Thanks a tonne for the update. Will be waiting for it.

**Comment by prabhuignoto** [comment]
@miral-zymr its fixed now. can you check and confirm if they are working as expected

**Comment by miral-zymr** [comment]
@prabhuignoto Thanks a lot. It's working now.
