### ISSUE TITLE
Custom icons renders only in HORIZONTAL mode

### ISSUE THREAD

**Issue by Krugerro** [prabhuignoto/react-chrono#328]
**Describe the bug**
Custom icons renders only in mode=HORIZONTAL

**To Reproduce**
Follow https://codesandbox.io/s/react-chrono-icon-bug-1leht3?file=/src/App.js
Switch mode to mode="VERTICAL" or mode="VERTICAL_ALTERNATING"

**Expected behavior**
Gear icon shows on first item in VERTICAL modes.

**Screenshots**
Please follow codesandbox.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser: Edge
 - Version :  Version 109.0.1518.78 

**Smartphone (please complete the following information):**
 not tested

**Comment by prabhuignoto** [comment]
@Krugerro this is now fixed #330
