### ISSUE TITLE
Horizontal chronologic view (match cards with timeline track)

### ISSUE THREAD

**Issue by asjustis** [prabhuignoto/react-chrono#342]
Hi, I am aiming to implement a long scrollable horizontal timeline, similar to what VERTICAL and VERTICAL_ALTERNATING modes provide. 

However, I cannot find a way to match the cards' position with the timeline markers. Below I add some images to better explain. How it would be possible to approach this?

 Result layout that I aim for (naturally, content would be not rotated) - simple or alternating - both modes would do fine:
<img width="1063" alt="Screenshot 2023-03-01 at 12 02 29" src="https://user-images.githubusercontent.com/1465112/222110977-9f859168-59f3-4166-9d98-e1dbf819f138.png">

Horizontal layout I manage to get at best so far:
<img width="1680" alt="Screenshot 2023-03-01 at 12 19 57" src="https://user-images.githubusercontent.com/1465112/222111383-95b16cd6-0256-45d9-831a-902e94eede00.png">

Using these properties:

```
<div
				style={{
					width: "5000px",
					height: "100vw",
					backgroundColor: "gold",
					//transform: "rotate(-90deg)",
				}}
			>
				<Timeline
					items={items}
					mode="HORIZONTAL"
					showAllCardsHorizontal
					scrollable
					borderLessCards
					cardPositionHorizontal={"TOP"}
					hideControls
				/>
			</div>
```

Thanks

**Comment by prabhuignoto** [comment]
this is currently a limitation as far as horizontal mode is concerned. but i am looking to add this feature to the 2.0 release

**Comment by asjustis** [comment]
@prabhuignoto got it, thanks. Looking forward to it! 

In the meantime, I was able to get that by manually finding timeline elements and adjusting CSS widths by hand. Seemed to work.
