### ISSUE TITLE
`timelinePointShape` does not seem to work with HORIZONTAL mode

### ISSUE THREAD

**Issue by lukyanov** [prabhuignoto/react-chrono#358]
**Describe the bug**

The timeline points are always square in the horizontal mode no matter what value `timelinePointShape` has.

**To Reproduce**
```
<Chrono items={timelineData} mode="HORIZONTAL" timelinePointShape="diamond" />
```

**Expected behavior**
The timeline dots are in the diamond shape.

**Additional context**
Btw, the default for the vertical mode is "circle", but it's always "square" for the horizontal mode.

**Comment by prabhuignoto** [comment]
@lukyanov this is now fixed in the latest release.
