### ISSUE TITLE
make an event active by clicked on the event

### ISSUE THREAD

**Issue by pkdyc** [prabhuignoto/react-chrono#362]
hi,
I want to collapse or expand my event message section when clicked on the the event.It that any possible way to do that?
I already check the code and document, i found that the main difference between an collapse or expand event is whether there is a "active" in the classname. It's any way i am change the status of an event?

**Comment by prabhuignoto** [comment]
@pkdyc At the moment, the `title` and `subTitle` cannot be collapsed; only the `titleDetails` can be collapsed. If you want the same click behavior for the title and subtitle, it's not currently possible. Please note that the "active" only refers to the currently selected timeline item and does not affect the collapse function.

**Comment by pkdyc** [comment]
ty, i will implement this by myself, thx for your quick reply again

**Comment by pkdyc** [comment]
ty, i will implement this by myself, thx for your quick reply again

**Comment by pkdyc** [comment]
ty, i will implement this by myself, thx for your quick reply again

**Comment by prabhuignoto** [comment]
@pkdyc You might want to have a look at the "rendering custom content" section on this [link](https://github.com/prabhuignoto/react-chrono#rendering-custom-content).
