### ISSUE TITLE
Background colour when using icons

### ISSUE THREAD

**Issue by iwt-marvynzalewski** [prabhuignoto/react-chrono#363]
**Describe the bug**
When I am implementing icons instead of shaped according to https://react-chrono.prabhumurthy.com/features/icons.html the shape is still visible. I dig a bit in the code and found the line that I don't fully understand why it's there. https://github.com/prabhuignoto/react-chrono/blob/master/src/components/timeline-elements/timeline-card/timeline-horizontal-card.styles.ts#L99 since it's exactly the attribute I find in my app that renders the background.

In the documentation, it doesn't seem to be the case. Maybe someone know why it's there and/or how to get rid of it without any kind of black DOM magic.

**Expected behavior**
That there's no background when using custom icons.

**Screenshots**
<img width="684" alt="Screenshot 2023-05-04 at 07 36 25" src="https://user-images.githubusercontent.com/60434260/236120039-a4e72927-0fa0-4658-b01e-6cc361d29f98.png">
<img width="713" alt="Screenshot 2023-05-04 at 07 36 17" src="https://user-images.githubusercontent.com/60434260/236120045-e077ca09-10e8-484b-9fb3-f4503847d0c4.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX Ventura
 - Browser Chrome

**Additional context**
```
<Chrono theme={chronoTheme} classNames={classNames} items={experiences}
          disableNavOnKey disableAutoScrollOnClick disableClickOnCircle hideControls activeItemIndex
           mode={!isMobile ? "VERTICAL_ALTERNATING" : "VERTICAL"}>
            <div className="chrono-icons">
                {experiences.map((experience) => <img className="icon" src="/house.svg" alt={`Icon for ${experience.cardTitle}/${experience.cardSubtitle}`}/>)}
            </div>
</Chrono>

**Comment by prabhuignoto** [comment]
@iwt-marvynzalewski thanks for reporting the issue. are you looking to get rid of the white circle when using icons. can you confirm?

**Comment by iwt-marvynzalewski** [comment]
Hi @prabhuignoto exactly this is what i'm looking for. :)

**Comment by prabhuignoto** [comment]
@iwt-marvynzalewski The [theme](https://react-chrono.prabhumurthy.com/customize/theme.html#theme) prop has been updated with an additional property called `iconBackgroundColor` which allows you to control the background color of the icon.
Use the latest version and let me know if you face any issues
