### ISSUE TITLE
HORIZONTAL mode not showing content with Nested Timeline

### ISSUE THREAD

**Issue by NoerNova** [prabhuignoto/react-chrono#364]
**Describe the bug**
With setting mode to 'HORIZONTAL' and data items that contained nested items object will not show contents.

**To Reproduce**
Codesanbox example:
https://codesandbox.io/s/show-all-cards-forked-ogu4k8?file=/src/data.js

**Screenshots**
![Screenshot 2566-05-06 at 01 20 44](https://user-images.githubusercontent.com/9565672/236538040-bd3d8cfb-14c4-4d9e-bda1-0c6d58465086.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser any
 - Version 2.1.2

**Comment by prabhuignoto** [comment]
@NoerNova This is now fixed, please go ahead and check this again with the latest version
