### ISSUE TITLE
Theme.cardDetailsColor does not work.

### ISSUE THREAD

**Issue by UnknownAMD** [prabhuignoto/react-chrono#367]
**Describe the bug**
the property cardDetailsColor in the theme prop does not work, as in it does not change the color and defaults to black

**To Reproduce**
make a timeline
try to set cardDetailsColor in the theme
see that it does nothing

**Expected behavior**
Supposed to change the color of the details text in the card

**Screenshots**
![image](https://user-images.githubusercontent.com/94629779/236673244-f4626e93-bd5e-4264-a93b-99ee28ee47d5.png)
![image](https://user-images.githubusercontent.com/94629779/236673252-717cad7a-8ec1-4e9e-9fa3-94d7db081a8b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser OperaGX and FireFox
 - Version Latest

**Additional context**
none.

**Comment by prabhuignoto** [comment]
@UnknownAMD this is now fixed in the latest version
