### ISSUE TITLE
Make whole card clickable via URL

### ISSUE THREAD

**Issue by eltel** [prabhuignoto/react-chrono#371]
**Is your feature request related to a problem? Please describe.**
I can only access the link by clicking on the title

**Describe the solution you'd like**
I'd like to be able to make the whole card clickable and go to the desired URL

**Describe alternatives you've considered**

**Additional context**
I think this would be extremely useful and a lot more intuitive

**Comment by prabhuignoto** [comment]
@eltel have you looked at the [custom rendering option](https://github.com/prabhuignoto/react-chrono/#rendering-custom-content). does this feature help you to achieve the end result
