### ISSUE TITLE
Warning: Prop `id` did not match.(Server-Client)

### ISSUE THREAD

**Issue by canptleon** [prabhuignoto/react-chrono#372]
**Describe the bug**
When I enter the page where I call the Chrono component, a warning comes up in the console.

**To Reproduce**
1. Go to page
2. Click on nothing
3. Scroll down to nothing
4. See warning at console

**Expected behavior**
Not getting this warning in console :)

**Screenshots**
![Screenshot 2023-05-25 at 16 01 54](https://github.com/prabhuignoto/react-chrono/assets/53756891/58cf31cb-aba5-4096-92ba-4f7aa7591536)

If you need more information, please specify in the comments.
 "@emotion/css": "11.5.0",
"@emotion/react": "11.0.0",
"@emotion/server": "11.4.0",
"@emotion/styled": "11.3.0",
"@rebass/grid": "6.1.0",
"react": "^18.2.0",
 "next": "^13.1.4",
"react-chrono": "^2.1.2",
"typescript": "4.3.5"

**Additional context**
Hi, first of all, thank you very much for this library, it's really modern. I got a warning while using it in my nextjs project, do you know the solution? Warning disappears from console when Chrono component is not rendered.

**Comment by alexnguyennz** [comment]
I am also getting this with Next.js 13 (app dir and client components) - using `react-chrono@2.2.0`. For me, the id I get references an empty div (with class `TimelineContentRender` so I assume it's for something) that is inserted below the main timeline code. Would appreciate any assistance with this.

**Comment by prabhuignoto** [comment]
@alexnguyennz @canptleon do you have a sandbox or a link to the github project where this issue can be reproduced?

**Comment by alexnguyennz** [comment]
Sure https://codesandbox.io/p/sandbox/small-waterfall-rkgs3u

**Comment by paulbfe** [comment]
@prabhuignoto I am also getting same error

**Comment by prabhuignoto** [comment]
@paulbfe just wondering if the solutions suggested [here](https://stackoverflow.com/questions/67176204/how-to-resolve-prop-id-did-not-match-server-react-tabs-30-client-react) work? let me know.

**Comment by prabhuignoto** [comment]
alternatively you can now disabled the auto id generation via a new prop `noUniqueId` as well
