### ISSUE TITLE
can not work in nextjs

### ISSUE THREAD

**Issue by Uni-h** [prabhuignoto/react-chrono#386]
When i used in Nextjs, it didn't work.
![image](https://github.com/prabhuignoto/react-chrono/assets/100669817/ac5187e8-8f7c-4cd8-9d4a-9663688110b4)
![image](https://github.com/prabhuignoto/react-chrono/assets/100669817/dfb8fdc1-4d02-43e9-a642-27f7566aef1d)
![image](https://github.com/prabhuignoto/react-chrono/assets/100669817/b00345ca-b56c-464d-9dff-5c3daf3598e5)

**Comment by prabhuignoto** [comment]
This is happening because of the recent upgrade of the styled-components library that react-chrono utilizes internally. A fix for this issue will be available soon. The fix will also resolve the warnings you are currently seeing on the console, which are unrelated to the broken timeline.

**Comment by prabhuignoto** [comment]
@Uni-h you can go ahead and try out now with the new release. also a few things to be noted while using the timeline in Next JS.

You need to disable the autoId generation via the new prop `noUniqueId` and pass your unique id via the `uniqueId` prop

Refer the props section for details and let me know if you need help

https://github.com/prabhuignoto/react-chrono#props
