### ISSUE TITLE
Compatibility react-native

### ISSUE THREAD

**Issue by JB712** [prabhuignoto/react-chrono#394]
Sorry if the information is available somewhere, but I couldn't find it 😅

I was looking for a timeline lib' and this one was the best I found ! But after few attempts I may have forgotten to check if this library is compatible with RN. Can someone confirm that this one is not compatible with RN ?

By the way this could be a great thing to become compatible 😇

**Comment by prabhuignoto** [comment]
@JB712 React Chrono is not supported for React Native, and there are currently no plans to build a version for RN
