### ISSUE TITLE
Text selection for copying

### ISSUE THREAD

**Issue by JoelGeorge693** [prabhuignoto/react-chrono#403]
Is there a way to copy the text that is on the card or the whole component? 

Currently I cannot select the text. 

Is it locked ? if it is can we do something to unlock this.

Really need this to be solved.

**Comment by prabhuignoto** [comment]
@JoelGeorge693 this is now fixed. please go ahead and check this with the latest version

**Comment by JoelGeorge693** [comment]
Hi,

If I am not mistaken the latest version of react-chrono is 2.1.2 right ?

If it is the case the text selection doesn't seem to work still. I hope you do understand the issue that I raised.

Otherwise, let me re-explain, like on any web app on a browser we can select the text that appears on it, after selection if turns blue and we can copy the text. I cannot seem to do that with any of the text in the whole component neither the text that appears on the card nor the title.

I hope this makes it clear and If you have solved the same issue mentioned above please guide me with the latest version of react-chrono.

Thanks in advance. 😊

**Comment by JoelGeorge693** [comment]
Thank you so much for your help 😊
