### ISSUE TITLE
'parseDetailsAsHTML' Does Not Appear to be Working 

### ISSUE THREAD

**Issue by eltel** [prabhuignoto/react-chrono#469]
**Describe the bug**
I've followed instructions to the letter regarding the use of parseDetailsAsHTML, I tried manually setting parseDetailsAsHTML={true} too, and the HTML tags were still visible, in both custom content and regular mode, vertical and horizonatal.
**To Reproduce**

**Expected behavior**
HTML tags to not be visible in my content and HTML tags to actually be applied/marked up
**Screenshots**
![image](https://github.com/prabhuignoto/react-chrono/assets/4655660/c29866f3-5f23-4ea5-b212-0ac6771d2784)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux Fedora
 - Browser [e.g. chrome, safari] Chrome/Firefox
 - Version [e.g. 22] Chrome Version 121.0.6167.160 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
The same issues occur in all formats/layouts content types.

Many thanks in advance if you can offer any advice!

**Comment by prabhuignoto** [comment]
@eltel can you share the codesandbox link or alternative one to reproduce this issue

**Comment by prabhuignoto** [comment]
closing this as invalid. please feel free to reopen if you are still having issues

**Comment by prabhuignoto** [comment]
closing this. please feel free to reopen if you are still having issues.

**Comment by tanmehar** [comment]
This issue still prevails @prabhuignoto 
parseDetailsAsHTML is prop is not working.
