### ISSUE TITLE
Add an option to hide the new Toolbar

### ISSUE THREAD

**Issue by jonnegrete** [prabhuignoto/react-chrono#477]
In the 2.5 update the new toolbar was added, and with it a prop to change it's position. But there is no easy way to hide it via props.

It would be nice to have an option to hide it easily.

Thank you!

**Comment by seriouscatsoserious** [comment]
how are you hiding it without the prop?

**Comment by prabhuignoto** [comment]
use the new prop `hideToolbar` to hide the toolbar completely. `hideControls` has been deprecated.

**Comment by jonnegrete** [comment]
Thank you!
