### ISSUE TITLE
Broken links in "Built with" section

### ISSUE THREAD

**Issue by sergeykish** [prabhuignoto/react-chrono#50]
Broken links in "Built with" section

**To Reproduce**
1. Go to https://github.com/prabhuignoto/react-chrono
2. Click on 'Typescript', 'emotion', 'snowpack'
4. See "Page not found" error

**Expected behavior**
It should open project page

**Comment by prabhuignoto** [comment]
fixed the broken links. thanks for reporting @sergeykish
