### ISSUE TITLE
OnLoad page autofocus on chrono

### ISSUE THREAD

**Issue by lohax** [prabhuignoto/react-chrono#71]
Hello,

I have a one page infinite scroll website and when loading the focus is setting on my react chrono.
If I put of the component, it's ok of course.
Is there a way to counter that please?

Best regards,
Loïc

**Comment by prabhuignoto** [comment]
could you please point me to the repo where this is happening.

thanks

**Comment by lohax** [comment]
You ca found it here : https://github.com/lohax/MonCvOnline
And yes, I'm using the last version 1.6
Thank you

**Comment by prabhuignoto** [comment]
thanks i am unable to run the repo locally. is there a gif you can attach to help me understand the problem better.

here is the error i see while running
error Problems with gatsby-source-contentful plugin options:
spaceId: undefined - "spaceId" is required
accessToken: undefined - "accessToken" is required

**Comment by lohax** [comment]
Yes, it's beacause of my CMS acces.
You can see it on : https://loic-chambost.dev

**Comment by prabhuignoto** [comment]
thanks. this needs to be fixed on the component. ill keep you posted on the patch/fix.

**Comment by lohax** [comment]
Thanks a lot for your work !

**Comment by prabhuignoto** [comment]
please update react-chrono to 1.6.1 and let me know how it works out for you.

**Comment by lohax** [comment]
It's ok with this new version !
Thanks a lot!
