### ISSUE TITLE
Bullet & Numbering in Timeline item Model

### ISSUE THREAD

**Issue by ranggabadrus** [prabhuignoto/react-chrono#76]
how i can show cardDetailedText as bullet or numbering text?

**Comment by prabhuignoto** [comment]
hi @ranggabadrus . welcome to react-chrono.

have  you tried using the custom rendering option. does this help
https://github.com/prabhuignoto/react-chrono#rendering-custom-content

https://codesandbox.io/s/react-chrono-vertical-custom-qepnm?file=/src/App.js
