### ISSUE TITLE
is it possible to change Card color?

### ISSUE THREAD

**Issue by pekadotai** [prabhuignoto/react-chrono#77]
how i can change Card color?

**Comment by prabhuignoto** [comment]
hi  @pekadotai ,  I've just made an update to the lib with support for changing cardColors. check it out and let me know how it  works out.

`<chrono items={items}  
     theme={{  cardBgColor: "yellow", cardForeColor: "violet" }}
 />`

**Comment by 4RSIM3R** [comment]
Hayy can you add more spesific theme rules.., thank you

**Comment by prabhuignoto** [comment]
@4RSIM3R yes more specific rules will be added in the next update. Is there a specific element that you are trying to color customize and that is missing at the moment.

**Comment by asoutheastasiandessert** [comment]
> hi @pekadotai , I've just made an update to the lib with support for changing cardColors. check it out and let me know how it works out.
> 
> `<chrono items={items} theme={{ cardBgColor: "yellow", cardForeColor: "violet" }} />`

it works. nice.
