### ISSUE TITLE
paginated items

### ISSUE THREAD

**Issue by Abror1997** [prabhuignoto/react-chrono#78]
First of all, thanks for the amazing project! I don't get the point of one thing. How to approach with server-side paginated items?

**Comment by prabhuignoto** [comment]
Hi  @Abror1997, Glad you liked the project. can you add more specifics on the use case.  What exactly you want to paginate.
Are you trying to use it in a f/w like Next.js.

**Comment by Abror1997** [comment]
@prabhuignoto hey thanks for the quick reply! I'm trying to achieve load more button. When I update items, Timeline doesn't update items.

**Comment by prabhuignoto** [comment]
@Abror1997 is  there a repo to check this. that would be helpful to understand

**Comment by Abror1997** [comment]
@prabhuignoto sure i make a sandbox and share asap

**Comment by Abror1997** [comment]
@prabhuignoto https://codesandbox.io/s/react-chrono--pagination-nhlvl

**Comment by prabhuignoto** [comment]
updating items in this manner are not supported at the moment.  but this will be patched along with the other updates i have planned for the weekend.

**Comment by prabhuignoto** [comment]
@Abror1997 this is now supported and published with the new version 1.8. feel free to try this out and let me know how it works out for you.

you have to pass a new prop `allowDynamicUpdate` to enable dynamic updates.

https://github.com/prabhuignoto/react-chrono#props

**Comment by Abror1997** [comment]
@prabhuignoto I've checked this, now items change dynamically, but there is another issue occured., when you set allowDynamicUpdate=true, the title not shown now. But I think, we change close the issue.

**Comment by prabhuignoto** [comment]
@Abror1997 the card title issue has been fixed with  #80.  can you check and let me know if you are still facing this issue.

**Comment by Abror1997** [comment]
@prabhuignoto Oh I see it works now, thanks!
