### ISSUE TITLE
Card titles not showing on timeline? 

### ISSUE THREAD

**Issue by derekxiao77** [prabhuignoto/react-chrono#79]
**Describe the bug**
I created a vertical timeline and passed in an items object of cards with title, cardTitle, and cardSubtitle. The timeline and cards are showing correctly, but the titles are not showing. 

**To Reproduce**
I just used the "getting started" code snippet". 

**Expected behavior**
I expected to see titles appear on the left side of the timeline to correspond with each card. 

**Screenshots**
<img width="1011" alt="Screen Shot 2020-11-29 at 9 46 54 PM" src="https://user-images.githubusercontent.com/16855070/100563553-a7629c80-328c-11eb-8a3a-919a139e6b8b.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome
 - Version: 87.0.4280.67

**Comment by prabhuignoto** [comment]
@derekxiao77 thanks for reporting the issue. this is now fixed. please check and let me know if you are still facing any issues.

**Comment by derekxiao77** [comment]
It's fixed now, thank you! Is it possible to control the font of the title and card text without custom rendering?

**Comment by prabhuignoto** [comment]
there is no font specific setting right now. ideally the component should  inherit the fonts from the container (if you have set one). 
is this not working already
