### ISSUE TITLE
Triggering onScroll event handler

### ISSUE THREAD

**Issue by LynchyC** [prabhuignoto/react-chrono#81]
Trying to implement a infinite scrolling Timeline where the component load more items when reaching the bottom of the list.

However, adding an `onScroll` event handler to the Chrono component does not trigger anything.

Is it possible to pass this along or to allow a ref to be passed to the component so an event listener can be added?

**Comment by prabhuignoto** [comment]
@LynchyC welcome to react-chrono. right now the component does not notify a `scrollEnd` event.

This will be supported in the next minor release planned for this week.

**Comment by prabhuignoto** [comment]
@LynchyC  added a new prop `onScrollEnd` to detect the end of the timeline.  please feel free to check out and let me know how it works out for you.
