### ISSUE TITLE
cardHeight prop not working

### ISSUE THREAD

**Issue by moaazassali** [prabhuignoto/react-chrono#88]
**Describe the bug**
I am adding cardHeight property to the Chrono component but nothing changes with the cards

**To Reproduce**
1. Add "cardHeight" to Chromo component

**Expected behavior**
From what I understand, the cardHeight property makes all cards have a certain minimum height. For example if I set it 1000, then all cards will have a minimum of 1000 pixels in height. However, in my case, the cards have the minimum height they need based on the text they occupy not the value I give.

**Screenshots**
https://imgur.com/a/PHGelk4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 1.8.4

**Comment by moaazassali** [comment]
I managed a workaround by adding to the cardsubtitle prop a div component instead which consists of text + multiple <br/> to achieved the desired height

**Comment by prabhuignoto** [comment]
@moaazassali this is been fixed with 1.8.5. update the lib and you should be able to set the height.
