### ISSUE TITLE
Cards missing in horizontal timeline in Gatsby production build

### ISSUE THREAD

**Issue by moaazassali** [prabhuignoto/react-chrono#89]
**Describe the bug**
When I run my gatsby app in development by using "yarn start" then the horizontal timeline works perfectly. However, if I want to publish a build by using "yarn build" then the cards of the timeline all disappear. I have included a link to relevant images below.

**To Reproduce**
1. Create a timeline with horizontal mode
2. Run "gatsby build" / "yarn build" / "npm build"
3. All cards will be missing from the timeline

**Expected behavior**
It is expected that all the cards appear normally just like in the development Gatsby build when running "yarn start." The issue only occurs when the final build is made by using "yarn build"

**Screenshots**
https://imgur.com/a/VPdVDBs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 1.8.4

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 10
 - Browser: Chrome
 - Version: 1.8.4

The device is not very relevant for this issue. It has to do with the final production build that Gatsby outputs. Since the production build Gatsby generates is "more optimized," I believe something gets messed up in that process since it doesn't happen in the development build. 

UPDATE: This issue only happens in the index page of the website when visited for the first time. For example, let's say the timeline is in the index page which I first land on. The cards in the horizontal line will not appear. If I go to another page then back to the index page, the timeline works as expected and the cards are there. 
I hope this could help narrow down the bug.

**Comment by prabhuignoto** [comment]
@moaazassali thanks for reporting the issue.

can you please share the link to repo to reproduce this.

**Comment by moaazassali** [comment]
> 
> 
> @moaazassali thanks for reporting the issue.
> 
> can you please share the link to the repo to reproduce this.

Here is the repo: https://github.com/moaazassali/genify-web-temp

After you download it, open the folder with VS Code (or another IDE) then run "yarn start." This will generate a page on localhost:8000 that has the timeline working properly. 
Then, terminate that operation and run "yarn build." After that is done, run "yarn serve" which will generate a page on localhost:9000 with the bug in the timeline that doesn't show the cards. If you head to Contact Us page (only functioning page in that repo other than home) from the header and back to Home then the timeline works properly.

**Comment by prabhuignoto** [comment]
@moaazassali  this is fixed with 1.8.5. tested it myself with the app and seems alright to me.

please check.

**Comment by moaazassali** [comment]
> 
> 
> @moaazassali this is fixed with 1.8.5. tested it myself with the app and seems alright to me.
> 
> please check.

Thanks a lot for the quick response. It works perfectly now!
