### ISSUE TITLE
Adding small images/icons to the clickable circles on the timeline

### ISSUE THREAD

**Issue by moaazassali** [prabhuignoto/react-chrono#91]
**Is your feature request related to a problem? Please describe.**
This is just a suggestion for the visual aspect of the timeline. Adding icons to the clickable circles of the timeline would be more visually appealing and convey some message while viewing the timeline and prior to clicking on the next event.

**Describe the solution you'd like**
A prop inside the objects in the items array for an icon/image.
This could simply add to the "style" of the circle div the property "background" which links to the link of the given icon. Preferably, a better solution would be to allow the addition of a div component (placed on top of the circle but still inside the circle borders), enabling greater customization.  

**Describe alternatives you've considered**
I have tried looking into the files of the library but I couldn't find the div relating to the circles

**Comment by prabhuignoto** [comment]
@moaazassali  with the #94 changes, you can add icons to the clickable circles.

check out the documentation [section](https://github.com/prabhuignoto/react-chrono#-custom-icons-for-the-timeline) and let me know how that works out for you.

Thanks for suggesting the idea
