### ISSUE TITLE
Divide the detailed text in paragraphs

### ISSUE THREAD

**Issue by juandeto** [prabhuignoto/react-chrono#92]
Hi Prabhu! Have you thought of transforming "cardDetailedText" in an object where you can order your info like:

cardDetailedText:{
                            paragraph1: lorempisum....,
                            paragraph2: new paragraph...
                            .
                            .
                            }

The library is really cool.

**Comment by prabhuignoto** [comment]
@juandeto thanks.

right now the only way to achieve something like this would be to use the custom rendering option.
[custom rendering](https://github.com/prabhuignoto/react-chrono#rendering-custom-content).

but this surely sounds like a very good idea as well.

**Comment by prabhuignoto** [comment]
@juandeto with #94 changes you can split large texts into individual paragraphs

- `cardDetailedText` will now also accept string of arrays. The array is split and placed as a separate text blocks.
   
   ```sh
      cardDetailedText: ['text1', 'text2]
   ```

please check out and let me know how that works out.

**Comment by juandeto** [comment]
Great! Thanks a lot, I will test it and let you know
